CREATE OR REPLACE PROCEDURE INSERTTIONTOSTOCKHISTORY 
IS
PRODUCT_ID1 NUMBER;
PRODUCT_ID2 NUMBER;
PRODUCT_NAME1 VARCHAR(255);
NO_OF_ITEMS1 NUMBER;
DATE_ITEM DATE;
TEMP NUMBER;
CURSOR STOCK_HISTORY_TABLE_CHECKING IS SELECT PRODUCT_ID FROM STOCKHISTORY WHERE STOCK_DATE=(TO_CHAR(SYSDATE)); 
CURSOR CUR_RECORD IS SELECT * FROM STOCK;
CURSOR STOCK_HAS_ENTRY IS SELECT NO_OF_ITEMS FROM STOCKHISTORY WHERE PRODUCT_ID=PRODUCT_ID1;

BEGIN 

OPEN STOCK_HISTORY_TABLE_CHECKING;
FETCH STOCK_HISTORY_TABLE_CHECKING INTO PRODUCT_ID1;

IF STOCK_HISTORY_TABLE_CHECKING%ROWCOUNT=0 THEN
OPEN CUR_RECORD;
CLOSE STOCK_HISTORY_TABLE_CHECKING;
LOOP
FETCH CUR_RECORD INTO PRODUCT_ID1,PRODUCT_NAME1,NO_OF_ITEMS1;
EXIT WHEN CUR_RECORD%NOTFOUND;
INSERT INTO STOCKHISTORY VALUES((TO_CHAR(SYSDATE)),PRODUCT_ID1,PRODUCT_NAME1,NO_OF_ITEMS1);
END LOOP;

CLOSE CUR_RECORD;

ELSE
OPEN CUR_RECORD;

LOOP
FETCH CUR_RECORD INTO PRODUCT_ID1,PRODUCT_NAME1,NO_OF_ITEMS1;
EXIT WHEN CUR_RECORD%NOTFOUND;
OPEN STOCK_HAS_ENTRY;
FETCH STOCK_HAS_ENTRY INTO TEMP;
IF STOCK_HAS_ENTRY%ROWCOUNT=1 THEN
UPDATE STOCKHISTORY SET NO_OF_ITEMS=NO_OF_ITEMS1 WHERE PRODUCT_ID=PRODUCT_ID1 AND STOCK_DATE=(TO_CHAR(SYSDATE));
ELSE
INSERT INTO STOCKHISTORY VALUES ((TO_CHAR(SYSDATE)),PRODUCT_ID1,PRODUCT_NAME1,NO_OF_ITEMS1);

END IF;
CLOSE STOCK_HAS_ENTRY;
END LOOP;

CLOSE CUR_RECORD;

END IF;



END INSERTTIONTOSTOCKHISTORY;
/
